FROM python:3.11-slim AS prod-stage

ENV PYTHONFAULTHANDLER=1 \
  PYTHONHASHSEED=random \
  PYTHONUNBUFFERED=1 \
  PIP_DEFAULT_TIMEOUT=100 \
  PIP_DISABLE_PIP_VERSION_CHECK=1 \
  PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY pyproject.toml poetry.lock app.py ./
COPY backend ./backend

RUN python -m pip install --upgrade pip && python -m pip install .

EXPOSE 9090
CMD ["python", "app.py"]